language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - echo "extension = snmp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install

script:
  - php -m | grep snmp
